apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-model
  labels:
    app: mnist-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-model
  template:
    metadata:
      labels:
        app: mnist-model
    spec:
      containers:
      - name: mnist-model
        image: mnist-model-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: mnist-model-service
  labels:
    app: mnist-model
spec:
  type: LoadBalancer
  selector:
    app: mnist-model
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
