apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-model
  labels:
    app: mnist-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mnist-model
  template:
    metadata:
      labels:
        app: mnist-model
    spec:
      containers:
      - name: mnist-model
        image: mlopsdemoacr.azurecr.io/mnist-model-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: "production"
        - name: CLOUD_PROVIDER
          value: "azure"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: mnist-model-service
  labels:
    app: mnist-model
spec:
  type: LoadBalancer
  selector:
    app: mnist-model
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mnist-model-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mnist-model
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
